// Icon generator script - run with Node.js if canvas is available
// Or manually create PNG files from the SVG files

const fs = require('fs');
const path = require('path');

// Simple 16x16 blue PNG with recording dot (base64)
const active16 = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA2ElEQVQ4T6WTvQ3CMBCFv0sJDUuQAeiYgBEYgREYgREYgQ1oKKFgCRYAKqQoyi/n5Fkv0Zvce5/PdwmMjAjrCzAHZsAE+AJvwAl4AC/gCHwUAJpYAfvIwBMogCNwBY7e8xLYJoAasAYOSeIDsAFunmDGAIkpVXARNJdA7HwDHICtBxgDpJyTgpOEmT+B3nvQCJCHsyLfOSmYSBCDGp6TgqGA3IGRgNyBkYDcAZkACfvDvwyuBzMQewO/4OXhQ+O3yvyFJJBLOX8daCUQ/wSoJRB2oJVA2IGQwA+UikUReZbBOgAAAABJRU5ErkJggg==', 'base64');

// Simple 48x48 blue PNG with recording dot (base64)
const active48 = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAA6ElEQVRoQ+2YQQ6AIAwA6f8f7fEp3jTxYILKQoFtCcYYwhY6pYXdEXzuQPl5AlgGsAxgGcAy4HMDL6LlRAI3oAKO/3wP7kBOxBuoH0+gAG7AETj4l1dgNQWoYw2c0hPfgDVw8Q5GOyB1JkU4l6DVAdz5DbDzJjvGAKlnUoVLFbbyJNB7EzQGKB3IHhwVLHVwVDAG6B3IHRwVzB2QMSDx/+FPDbcH8xFHe+CfePt50/nL5r5JAqWW0+eGVgXJPwNaBhQdaBlQdCBkQNL/8C+N64P5E8feQL/w+vGu8dvK/AtJoDRy+jnQqiDZgQ+IHl4xpzj1GAAAAABJRU5ErkJggg==', 'base64');

// Simple 128x128 blue PNG with recording dot (base64)  
const active128 = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAA+0lEQVR4Xu3VQQ0AIRDAwOL+hW4hxkPkGdxJ+8z8zgzgFbABYgNEBigHiA0QGaAcIDZAZIBygNgAkQHKAWIDRAYoB4gNEBmgHCA2QGSAcoDYAJEBygFiA0QGKAeIDRAZoBwgNkBkgHKA2ACRAcoBYgNEBigHiA0QGaAcIDZAZIBygNgAkQHKAWIDRAYoB4gNEBmgHCA2QGSAcoDYAJEBygFiA0QGKAeIDRAZoBwgNkBkgHKA2ACRAcoBYgNEBigHiA0QGaAcIDZAZIBygNgAkQHKAWIDRAYoB4gNEBmgHCA2QGSAcoDYAJEBygFiA0QGKAeIDRAZoBzgA2xKADEAlVtRAAAAAElFTkSuQmCC', 'base64');

// Grayscale versions for paused state
const paused16 = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA1ElEQVQ4T6WTuw3CQBBEZxcS0gIJFRBTAiVQAiVQAiVQAmkJCSmhBRAg8Ufn02rPb3Q/WNrRvNnZu5PAyEiw7oE5MAMmwBt4Aw/gCTyBI/BRAGhiBewjA0+gAI7ADTh6z0tglQBqwBo4JIkvwAa4eYIZAySmVMFF0FwCsfMNsAE2HmAMkHJOCk4SZv4Eeu9BI0AezopsZ6VgIkEManhWCoYCcgdGAnIHRgJyB2QCJOwP/zK4HsxA7A38gpeHD43fKvMXkkAu5fx1oJVA/BOglkDYgVYCYQdCAj8aREcRE0JvtwAAAABJRU5ErkJggg==', 'base64');

const paused48 = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAA30lEQVRoQ+2YQQ6AIAwA6f8f7fEp3jTxYILKQoFtCUYTwzK0pYXdEXzuQPl5AlgGsAxgGcAy4HMDr0TLiQRuQAUc//ke3IGciDdQP55AAdyAI3DwL6/AagpQxxo4pSe+AWvg4h2MdkDqTIpwLkGrA7jzG2DnTXaMAVLPpAqXKmzlSaD3JmgMUDqQPTgqWOrgqGAM0DuQOzgqmDsgYkDi/8OfGm4P5iOO9sA/8fbxpvOXzX2TBEotp88NrQqSfwa0DCg60DKg6EDIgKT/4V8a1wfzJ469gX7h9eNd47eV+QtJoNRy+tzQqiDZgQ/gN14xFIJuWwAAAABJRU5ErkJggg==', 'base64');

const paused128 = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAA9klEQVR4Xu3VQQ0AIRDAwOL+hW4hxkPkGdxJ+8z8zgzgFbABYgNEBigHiA0QGaAcIDZAZIBygNgAkQHKAWIDRAYoB4gNEBmgHCA2QGSAcoDYAJEBygFiA0QGKAeIDRAZoBwgNkBkgHKA2ACRAcoBYgNEBigHiA0QGaAcIDZAZIBygNgAkQHKAWIDRAYoB4gNEBmgHCA2QGSAcoDYAJEBygFiA0QGKAeIDRAZoBwgNkBkgHKA2ACRAcoBYgNEBigHiA0QGaAcIDZAZIBygNgAkQHKAWIDRAYoB4gNEBmgHCA2QGSAcoDYAJEBygFiA0QGKAfYADY1ADGqfOC+AAAAAElFTkSuQmCC', 'base64');

// Write PNG files
fs.writeFileSync('active-16.png', active16);
fs.writeFileSync('active-48.png', active48);
fs.writeFileSync('active-128.png', active128);
fs.writeFileSync('paused-16.png', paused16);
fs.writeFileSync('paused-48.png', paused48);
fs.writeFileSync('paused-128.png', paused128);

console.log('Icons generated!');
